# 接口示例

### 获取验证码

POST http://{{host}}/code/send
Content-Type: application/json

{
  "email": "burthuang@foxmail.com"
}

### 创建用户
POST http://{{host}}/user/create
Content-Type: application/json

{
  "email": "burthuang@foxmail.com",
  "username": "admin",
  "password": "123456",
  "code": "710292"
}

### 用户登录
POST http://{{host}}/user/login
Content-Type: application/json

{
  "username": "sysadmin",
  "password": "123456"
}


### 创建标签
POST http://{{host}}/tag/create
Content-Type: application/json

{
  "label": "电子产品",
  "icon": "shopping",
  "type": 0
}
